services:
  - type: web
    name: vidgrab-server
    env: node
    plan: free
    branch: kele
    buildCommand: "npm ci && npm run build"
    startCommand: "npm run start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: NODE_ENV
        value: "production"
